export const types = {
LOGIN_LOADING:"LOGIN_LOADING",
LOGIN_REQUEST:"LOGIN_REQUEST",
LOGIN_REQUEST_ERROR:"LOGIN_REQUEST_ERROR",
SIGNUP_LOADING:"SIGNUP_LOADING",
SIGNUP_REQUEST:"SIGNUP_REQUEST",
SIGNUP_REQUEST_ERROR:"SIGNUP_REQUEST_ERROR"
};