export const types = {
LOGIN_LOADING:"LOGIN_LOADING",
LOGIN_REQUEST:"LOGIN_REQUEST",
LOGIN_REQUEST_ERROR:"LOGIN_REQUEST_ERROR",
SIGNUP_LOADING:"SIGNUP_LOADING",
SIGNUP_REQUEST:"SIGNUP_REQUEST",
SIGNUP_REQUEST_ERROR:"SIGNUP_REQUEST_ERROR",
GET_COMPANIES_LOADING:"GET_COMPANIESLOADING",
GET_COMPANIES_REQUEST:"GET_COMPANIES_REQUEST",
GET_COMPANIES_REQUEST_ERROR:"GET_COMPANIES_REQUEST_ERROR",
GET_EMPLOYEES_LOADING:"GET_EMPLOYEES_LOADING",
GET_EMPLOYEES_REQUEST:"GET_EMPLOYEES_REQUEST",
GET_EMPLOYEES_REQUEST_ERROR:"GET_EMPLOYEES_REQUEST_ERROR"
};